services:
  backend:
    image: eido-backend
    container_name: eido-backend
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      SECRET_KEY: "super-secret-key"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 myapp.com"

      # Database
      DATABASE_NAME: "mydb"
      DATABASE_USER: "myuser"
      DATABASE_PASSWORD: "mypassword"
      DATABASE_HOST: "10.0.10.51"
      DATABASE_PORT: "5432"

      # CORS
      CORS_ALLOWED_ORIGINS: "http://localhost:3000 http://127.0.0.1:3000 https://myapp.com"
