services:
  backend:
    image: eido-backend
    container_name: eido_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      SECRET_KEY: "super-secret-key"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 add_your_domain"
      DATABASE_NAME: "add_your_db_name"
      DATABASE_USER: "add_your_db_user"
      DATABASE_PASSWORD: "add_your_db_password"
      DATABASE_HOST: "add_your_hostname"
      DATABASE_PORT: "add_your_db_port_number"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000 http://127.0.0.1:3000 add_your_domain"

  db:
    image: postgres:latest
    container_name: eido_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: add_your_db_user
      POSTGRES_PASSWORD: add_your_db_password
      POSTGRES_DB: add_your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: eido-frontend
    container_name: eido_frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE_URL: "http://add_your_domain/api"

volumes:
  postgres_data:
